### ISSUE TITLE
Support for ServiceStack.Text >= 4.0.42

### ISSUE THREAD

**Issue by nvisage-gf** [AnthonyCarl/NodaTime.Serialization.ServiceStackText#5]
Hi,

Recently updated our project to use latest ServiceStack release which caused an issue with current 1.2.17 version from NuGet as latest ServiceStack.Text does not have .net3.5-clientprofile.

I've forked and added support for it here: https://github.com/nvisage-gf/NodaTime.Serialization.ServiceStackText/tree/feature/ServiceStack_v4.0.42

Updated to .NET 4.0 profile and latest ServiceStack.Text + NodaTime assemblies.

NuGet (beta) package on our MyGet feed here: http://www.symbolsource.org/MyGet/Metadata/nvisage-psm/Project/NodaTime.Serialization.ServiceStackText

I can submit pull request if required; though you may want to review changes before.

Regards,

Gavin

**Comment by nvisage-gf** [comment]
This would break support for ServiceStack v3 using .NET 3.5 profile - though perhaps using the earlier 1.2.* version would suffice for this?

**Comment by AnthonyCarl** [comment]
It looks like the newer versions of `ServiceStack.Text` use something in the framework that isn't compatible with .Net v3.5. I am able to recreate the issue with the v4 test suite.

I believe I can simple re-build the library targeting .Net v4 and include framework specific binaries in the Nuget package. It looks like you didn't change any actual C# code in your pull request.

**Comment by nvisage-gf** [comment]
Correct I did not change anything; just rebuilt against .NET v4 with updated binaries. Thanks.

**Comment by AnthonyCarl** [comment]
I found the problem, the deserialize function delegate was change from a field to a property.

We still use ServiceStack v3.9.xx, so I want to maintain compatibility. I have a working fix that I need to cleanup and should be able to get it done very soon. Thankfully ServcieStack did not change the name of the field/property, so the solution is to reflect for the field and if that is not present, to reflect for the property.

**Comment by AnthonyCarl** [comment]
This change has been published to Nuget.org (https://www.nuget.org/packages/NodaTime.Serialization.ServiceStackText/1.2.18).

**Comment by AnthonyCarl** [comment]
To close the loop, here is the breaking change commit to ServiceStack.Text: https://github.com/ServiceStack/ServiceStack.Text/commit/43d3882e0464265f771372d98b693083a5d84637

**Comment by stronachconsult** [comment]
Thanks to both of you for this. I wish I had checked the outstanding issues as I forked and did a similar fix on the deserialize delegate property just 2 days ago. Was going to submit a pull request but no need if this is fixed and working...
